---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: create a test file
      file:
        path: /tmp/vms.log
        state: touch
        mode: '0644'

  roles:
    - role: apps_fluentbit

  vars:
    fluentbit_inputs:
      - name: tail
        alias: vms
        tag: vms
        path: /tmp/vms.log
        db: /tmp/vms.db
        parser: syslog
    fluentbit_filters:
      - name: modify
        alias: add_from_syslog
        match: '*'
        type: Add
        value: 'from_syslog true'
    fluentbit_outputs:
      - name: null
        match: '*'
    fluentbit_parsers:
      - name: syslog
        format: regex
        regex: '^(?<register_time>[^ ]*) (?<source>[^ ]*) (?<level>[^ ]*) *(?<message>.*)$'
        time_key: time
        time_format: '%Y-%m-%dT%H:%M:%S %z'
        time_keep: on
